language: php

sudo: false

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.6
        - php: 5.6
          env: deps=low
        - php: 7.0
        - php: hhvm
        - php: nightly
        - php: nightly
          env: deps=low

before_script:
    - phpenv config-rm xdebug.ini || true
    - composer self-update
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/behat
    - vendor/bin/phpunit
